 spring:
  application:
    name: server
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pruebas
    username: root
    password: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  logging:
    level:
      ROOT: INFO