 spring:
  application:
    name: server
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    username: test
    password: 1234
    url: jdbc:mysql://localhost:3306/tic1
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddl-auto: update
      search:
        default:
          indexmanager: elasticsearch
          elasticsearch:
            host: <Elasticsearch-url>
            index_schema_management_strategy: drop-and-create
            required_index_status: yellow
  logging:
    level:
      ROOT: INFO